### PR TITLE
Swift 3 support

### LINKED ISSUE #21: Add support for Swift Package Manager

### LINKED ISSUE #22: Support Travis CI

### LINKED ISSUE #23: Linux support

### LINKED ISSUE #30: Buffer pointer instead of uint8 array generator
First, you have a great packer. 
I have only one idea or suggestion.
Did you think about using the UnsafePointer < UInt8 > instead of [Uint8]?
It would be faster for unpacking the strings because you can advance pointer for n places instead of using generator that is always advancing for one next byte.

Check this performance improvements that are used in swift for unpacking bytes packed with similar flatbuffers protocol: 
https://medium.com/@icex33/10-thousand-times-faster-swift-737b1accd973#.x9281mi2x

### LINKED ISSUE #32: Swift 3 support

### PR DESCRIPTION
**Pull request by a2**
Closes #21.
Closes #22.
Closes #23.
Closes #30.
Closes #32.

### CODE REVIEW

**Comment by umverteiler** [comment]
Great - thank you for this Swift Migration ;-)
I'm missing the Xcode Project File in the latest commit - is this by mistake?

**Comment by a2** [comment]
@LordNali You can generate the Xcode project file with `swift package generate-xcodeproj`.

**Comment by umverteiler** [comment]
Okay - should have thought of that (but haven´t used SPM yet).

**Comment by a2** [comment]
@LordNali No worries. I'll update the README to include this information.

**Comment by umverteiler** [comment]
Okay, now I got a problem with Carthage: It needs a shared Xcode-Project to build your Framework. 
The Problem is known: https://github.com/Carthage/Carthage/issues/1226
For now I manually create the necessary MessagePack project.

**Pull request merged**
