### PR TITLE
Feature/raw contains string or data

### PR DESCRIPTION
**Pull request by umverteiler**
Previous MessagePack versions use type raw for sending string **or** binary data. The user itself has to decide if the data should be handled as a string or NSData. Your current MessagePack.swift implementation always assumes the new MessagePack Specification: String and Binary have their own types. For this reason I introduced a compatibility mode (MSGP_COMPATIBILITY_MODE).

Additional I fixed the length detection for unsigned integers and the new binary type.

### CODE REVIEW

**Comment by a2** [comment]
What was wrong with the length detection for unsigned integers?

**Comment by umverteiler** [comment]
Actually there´s nothing wrong with your implementation, my bad. I thought we had the same situation like in the previous pull request / wrong length detection for array 16 and array 32. I just tried it and it work´s perfectly.

But there´s still an issue with `int64`: The length should be 8 (bytes) and not 2 (bytes). And there´s the question regarding the MessagePack Compatibility mode.

Should we close this pull request and I'll make a new one?

**Comment by a2** [comment]
Let's definitely tackle one problem per PR if that's okay.

**Comment by umverteiler** [comment]
OK, I´ll close this one and made a new one.

**Pull request closed without merging**
